AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - config.ru
    - Guardfile
    - vendor/**/*
    - .bundle/**/*
    - config/**/*
    - db/**/*
    - spec/rails_helper.rb
    - lib/tasks/**/*
    - Rakefile
    - Gemfile
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: exploded
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples', 'shared_context', 'scenario']
Metrics/LineLength:
  Max: 100
  Exclude:
    - spec/**/*
